import scrapy
from vinyl_crawler.items import Listing

class RecordlistingsPySpider(scrapy.Spider):
    name = 'discogsListings'
    allowed_domains = ['www.discogs.com']
    listings = []

    def start_requests(self):
        urls = ['https://www.discogs.com/seller/']
                
        genres = ['&genre=Electronic',
                  '&genre=Latin',
                  '&genre=Hip+Hop',
                  '&genre=Jazz',
                  '&genre=Folk%2C+World%2C+%26+Country',
                  '&genre=Classical',
                  '&genre=Stage+%26+Screen',
                  '&genre=Blues',
                  '&genre=Non-Music',
                  '&genre=Reggae',
                  '&genre=Children%27s',
                  '&genre=Brass+%26+Military'
                  '&genre=Funk+%2F+Soul',
                  '&genre=Pop',
                  '&genre=Rock',
                  ]

        styles = [
                '&style=Boogie+Woogie',
                '&style=Chicago+Blues',
                '&style=Country+Blues',
                '&style=Delta+Blues',
                '&style=East+Coast+Blues',
                '&style=Electric+Blues',
                '&style=Harmonica+Blues',
                '&style=Hill+Country+Blues',
                '&style=Jump+Blues',
                '&style=Louisiana+Blues',
                '&style=Memphis+Blues',
                '&style=Modern+Electric+Blues',
                '&style=Piano+Blues',
                '&style=Piedmont+Blues',
                '&style=Texas+Blues',
                '&style=Brass+Band',
                '&style=Marches',
                '&style=Military',
                '&style=Pipe+&+Drum',
                '&style=Educational',
                '&style=Nursery+Rhymes',
                '&style=Story',
                '&style=Baroque',
                '&style=Choral',
                '&style=Classical',
                '&style=Contemporary',
                '&style=Early',
                '&style=Impressionist',
                '&style=Medieval',
                '&style=Modern',
                '&style=Neo-Classical',
                '&style=Neo-Romantic',
                '&style=Opera',
                '&style=Operetta',
                '&style=Oratorio',
                '&style=Post-Modern',
                '&style=Renaissance',
                '&style=Romantic',
                '&style=Serial',
                '&style=Twelve-tone',
                '&style=Zarzuela',
                '&style=Abstract',
                '&style=Acid',
                '&style=Acid+House',
                '&style=Acid+Jazz',
                '&style=Ambient',
                '&style=Ballroom',
                '&style=Baltimore+Club',
                '&style=Bassline',
                '&style=Beatdown',
                '&style=Berlin-School',
                '&style=Big+Beat',
                '&style=Bleep',
                '&style=Breakbeat',
                '&style=Breakcore',
                '&style=Breaks',
                '&style=Broken+Beat',
                '&style=Chillwave',
                '&style=Chiptune',
                '&style=Dance-pop',
                '&style=Dark+Ambient',
                '&style=Darkwave',
                '&style=Deep+House',
                '&style=Deep+Techno',
                '&style=Disco',
                '&style=Disco+Polo',
                '&style=Donk',
                '&style=Doomcore',
                '&style=Downtempo',
                '&style=Drone',
                '&style=Drum+n+Bass',
                '&style=Dub',
                '&style=Dub+Techno',
                '&style=Dubstep',
                '&style=Dungeon+Synth',
                '&style=EBM',
                '&style=Electro',
                '&style=Electro+House',
                '&style=Electro+Swing',
                '&style=Electroacoustic',
                '&style=Electroclash',
                '&style=Euro+House',
                '&style=Euro-Disco',
                '&style=Eurobeat',
                '&style=Eurodance',
                '&style=Experimental',
                '&style=Footwork',
                '&style=Freestyle',
                '&style=Funkot',
                '&style=Future+Jazz',
                '&style=Gabber',
                '&style=Garage+House',
                '&style=Ghetto',
                '&style=Ghetto+House',
                '&style=Ghettotech',
                '&style=Glitch',
                '&style=Glitch+Hop',
                '&style=Goa+Trance',
                '&style=Grime',
                '&style=Halftime',
                '&style=Hands+Up',
                '&style=Happy+Hardcore',
                '&style=Hard+Beat',
                '&style=Hard+House',
                '&style=Hard+Techno',
                '&style=Hard+Trance',
                '&style=Hardcore',
                '&style=Hardstyle',
                '&style=Harsh+Noise+Wall',
                '&style=Hi+NRG',
                '&style=Hip+Hop',
                '&style=Hip-House',
                '&style=House',
                '&style=IDM',
                '&style=Illbient',
                '&style=Industrial',
                '&style=Italo+House',
                '&style=Italo-Disco',
                '&style=Italodance',
                '&style=J-Core',
                '&style=Jazzdance',
                '&style=Jersey+Club',
                '&style=Juke',
                '&style=Jumpstyle',
                '&style=Jungle',
                '&style=Latin',
                '&style=Leftfield',
                '&style=Lento+Violento',
                '&style=Makina',
                '&style=Minimal',
                '&style=Minimal+Techno',
                '&style=Modern+Classical',
                '&style=Moombahton',
                '&style=Musique+Concrète',
                '&style=Neo+Trance',
                '&style=Neofolk',
                '&style=Nerdcore+Techno',
                '&style=New+Age',
                '&style=New+Beat',
                '&style=Noise',
                '&style=Nu-Disco',
                '&style=Power+Electronics',
                '&style=Progressive+Breaks',
                '&style=Progressive+House',
                '&style=Progressive+Trance',
                '&style=Psy-Trance',
                '&style=Rhythmic+Noise',
                '&style=Schranz',
                '&style=Skweee',
                '&style=Sound+Collage',
                '&style=Speed+Garage',
                '&style=Speedcore',
                '&style=Synth-pop',
                '&style=Synthwave',
                '&style=Tech+House',
                '&style=Tech+Trance',
                '&style=Techno',
                '&style=Trance',
                '&style=Tribal',
                '&style=Tribal+House',
                '&style=Trip+Hop',
                '&style=Tropical+House',
                '&style=UK+Funky',
                '&style=UK+Garage',
                '&style=Vaporwave',
                '&style=Witch+House',
                '&style=Aboriginal',
                '&style=African',
                '&style=Andalusian+Classical',
                '&style=Andean+Music',
                '&style=Appalachian+Music',
                '&style=Bangladeshi+Classical',
                '&style=Basque+Music',
                '&style=Bengali+Music',
                '&style=Bhangra',
                '&style=Bluegrass',
                '&style=Cajun',
                '&style=Cambodian+Classical',
                '&style=Canzone+Napoletana',
                '&style=Carnatic',
                '&style=Catalan+Music',
                '&style=Celtic',
                '&style=Chacarera',
                '&style=Chamamé',
                '&style=Chinese+Classical',
                '&style=Chutney',
                '&style=Cobla',
                '&style=Copla',
                '&style=Country',
                '&style=Cretan',
                '&style=Dangdut',
                '&style=Éntekhno',
                '&style=Fado',
                '&style=Filk',
                '&style=Flamenco',
                '&style=Folk',
                '&style=Funaná',
                '&style=Gagaku',
                '&style=Galician+Traditional',
                '&style=Gamelan',
                '&style=Għana',
                '&style=Ghazal',
                '&style=Griot',
                '&style=Guarania',
                '&style=Gwo+Ka',
                '&style=Hawaiian',
                '&style=Highlife',
                '&style=Hillbilly',
                '&style=Hindustani',
                '&style=Honky+Tonk',
                '&style=Huayno',
                '&style=Indian+Classical',
                '&style=Jota',
                '&style=Jug+Band',
                '&style=Kaseko',
                '&style=Keroncong',
                '&style=Kizomba',
                '&style=Klasik',
                '&style=Klezmer',
                '&style=Korean+Court+Music',
                '&style=Laïkó',
                '&style=Lao+Music',
                '&style=Liscio',
                '&style=Luk+Krung',
                '&style=Luk+Thung',
                '&style=Maloya',
                '&style=Mbalax',
                '&style=Min’yō',
                '&style=Mizrahi',
                '&style=Mo+Lam',
                '&style=Morna',
                '&style=Mouth+Music',
                '&style=Mugham',
                '&style=Népzene',
                '&style=Nhạc+Vàng',
                '&style=Nordic',
                '&style=Ottoman+Classical',
                '&style=Overtone+Singing',
                '&style=Pacific',
                '&style=Pasodoble',
                '&style=Persian+Classical',
                '&style=Philippine+Classical',
                '&style=Phleng+Phuea+Chiwit',
                '&style=Piobaireachd',
                '&style=Polka',
                '&style=Progressive+Bluegrass',
                '&style=Qawwali',
                '&style=Raï',
                '&style=Rebetiko',
                '&style=Romani',
                '&style=Rune+Singing',
                '&style=Salegy',
                '&style=Sámi+Music',
                '&style=Sea+Shanties',
                '&style=Séga',
                '&style=Sephardic',
                '&style=Soukous',
                '&style=Taarab',
                '&style=Tamil+Film+Music',
                '&style=Thai+Classical',
                '&style=Volksmusik',
                '&style=Waiata',
                '&style=Western+Swing',
                '&style=Yemenite+Jewish',
                '&style=Zamba',
                '&style=Zemer+Ivri',
                '&style=Zouk',
                '&style=Zydeco',
                '&style=Bayou+Funk',
                '&style=Boogie',
                '&style=Contemporary+R&B',
                '&style=Free+Funk',
                '&style=Funk',
                '&style=Gogo',
                '&style=Gospel',
                '&style=Minneapolis+Sound',
                '&style=Neo+Soul',
                '&style=New+Jack+Swing',
                '&style=P.Funk',
                '&style=Psychedelic',
                '&style=Rhythm+&+Blues',
                '&style=Soul',
                '&style=Swingbeat',
                '&style=UK+Street+Soul',
                '&style=Bass+Music',
                '&style=Beatbox',
                '&style=Bongo+Flava',
                '&style=Boom+Bap',
                '&style=Bounce',
                '&style=Britcore',
                '&style=Cloud+Rap',
                '&style=Conscious',
                '&style=Crunk',
                '&style=Cut-up/DJ',
                '&style=DJ+Battle+Tool',
                '&style=Favela+Funk',
                '&style=G-Funk',
                '&style=Gangsta',
                '&style=Go-Go',
                '&style=Hardcore+Hip-Hop',
                '&style=Hiplife',
                '&style=Horrorcore',
                '&style=Hyphy',
                '&style=Instrumental',
                '&style=Jazzy+Hip-Hop',
                '&style=Kwaito',
                '&style=Miami+Bass',
                '&style=Motswako',
                '&style=Phonk',
                '&style=Pop+Rap',
                '&style=Ragga+HipHop',
                '&style=RnB/Swing',
                '&style=Screw',
                '&style=Spaza',
                '&style=Thug+Rap',
                '&style=Trap',
                '&style=Turntablism',
                '&style=Afro-Cuban+Jazz',
                '&style=Afrobeat',
                '&style=Avant-garde+Jazz',
                '&style=Big+Band',
                '&style=Bop',
                '&style=Bossa+Nova',
                '&style=Cape+Jazz',
                '&style=Contemporary+Jazz',
                '&style=Cool+Jazz',
                '&style=Dark+Jazz',
                '&style=Dixieland',
                '&style=Easy+Listening',
                '&style=Free+Improvisation',
                '&style=Free+Jazz',
                '&style=Fusion',
                '&style=Gypsy+Jazz',
                '&style=Hard+Bop',
                '&style=Jazz-Funk',
                '&style=Jazz-Rock',
                '&style=Latin+Jazz',
                '&style=Modal',
                '&style=Post+Bop',
                '&style=Ragtime',
                '&style=Smooth+Jazz',
                '&style=Soul-Jazz',
                '&style=Space-Age',
                '&style=Stride',
                '&style=Swing',
                '&style=Afro-Cuban',
                '&style=Aguinaldo',
                '&style=Axé',
                '&style=Bachata',
                '&style=Baião',
                '&style=Bambuco',
                '&style=Batucada',
                '&style=Beguine',
                '&style=Bolero',
                '&style=Bomba',
                '&style=Boogaloo',
                '&style=Bossanova',
                '&style=Candombe',
                '&style=Carimbó',
                '&style=Cha-Cha',
                '&style=Champeta',
                '&style=Charanga',
                '&style=Choro',
                '&style=Compas',
                '&style=Conjunto',
                '&style=Corrido',
                '&style=Cuatro',
                '&style=Cubano',
                '&style=Cumbia',
                '&style=Danzon',
                '&style=Descarga',
                '&style=Forró',
                '&style=Gaita',
                '&style=Guaguancó',
                '&style=Guajira',
                '&style=Guaracha',
                '&style=Jibaro',
                '&style=Joropo',
                '&style=Lambada',
                '&style=Mambo',
                '&style=Marcha+Carnavalesca',
                '&style=Mariachi',
                '&style=Marimba',
                '&style=Merengue',
                '&style=MPB',
                '&style=Musette',
                '&style=Música+Criolla',
                '&style=Norteño',
                '&style=Nueva+Cancion',
                '&style=Nueva+Trova',
                '&style=Occitan',
                '&style=Pachanga',
                '&style=Plena',
                '&style=Porro',
                '&style=Quechua',
                '&style=Ranchera',
                '&style=Reggaeton',
                '&style=Rumba',
                '&style=Salsa',
                '&style=Samba',
                '&style=Samba-Canção',
                '&style=Seresta',
                '&style=Son',
                '&style=Son+Montuno',
                '&style=Sonero',
                '&style=Tango',
                '&style=Tejano',
                '&style=Timba',
                '&style=Trova',
                '&style=Vallenato',
                '&style=Audiobook',
                '&style=Comedy',
                '&style=Dialogue',
                '&style=Education',
                '&style=Erotic',
                '&style=Field+Recording',
                '&style=Health-Fitness',
                '&style=Interview',
                '&style=Monolog',
                '&style=Movie+Effects',
                '&style=Poetry',
                '&style=Political',
                '&style=Promotional',
                '&style=Public+Broadcast',
                '&style=Public+ServiceAnnouncement',
                '&style=Radioplay',
                '&style=Religious',
                '&style=Sermon',
                '&style=Sound+Art',
                '&style=Sound+Poetry',
                '&style=Special+Effects',
                '&style=Speech',
                '&style=Spoken+Word',
                '&style=Technical',
                '&style=Therapy',
                '&style=Ballad',
                '&style=Barbershop',
                '&style=Bollywood',
                '&style=Break-In',
                '&style=Bubblegum',
                '&style=Cantopop',
                '&style=Chanson',
                '&style=City+Pop',
                '&style=Enka',
                '&style=Ethno-pop',
                '&style=Europop',
                '&style=Hokkien+Pop',
                '&style=Indie+Pop',
                '&style=Indo-Pop',
                '&style=J-pop',
                '&style=K-pop',
                '&style=Karaoke',
                '&style=Kayōkyoku',
                '&style=Levenslied',
                '&style=Light+Music',
                '&style=Mandopop',
                '&style=Music+Hall',
                '&style=Néo+Kyma',
                '&style=Novelty',
                '&style=Ryūkōka',
                '&style=Schlager',
                '&style=Villancicos',
                '&style=Vocal',
                '&style=Azonto',
                '&style=Bubbling',
                '&style=Calypso',
                '&style=Dancehall',
                '&style=Dub+Poetry',
                '&style=Junkanoo',
                '&style=Lovers+Rock',
                '&style=Mento',
                '&style=Ragga',
                '&style=Rapso',
                '&style=Reggae',
                '&style=Reggae+Gospel',
                '&style=Reggae-Pop',
                '&style=Rocksteady',
                '&style=Roots+Reggae',
                '&style=Soca',
                '&style=Steel+Band',
                '&style=Acid+Rock',
                '&style=Acoustic',
                '&style=Alternative+Rock',
                '&style=AOR',
                '&style=Arena+Rock',
                '&style=Art+Rock',
                '&style=Atmospheric+Black+Metal',
                '&style=Avantgarde',
                '&style=Beat',
                '&style=Black+Metal',
                '&style=Blues+Rock',
                '&style=Brit+Pop',
                '&style=Classic+Rock',
                '&style=Coldwave',
                '&style=Country+Rock',
                '&style=Crust',
                '&style=Death+Metal',
                '&style=Deathcore',
                '&style=Deathrock',
                '&style=Depressive+Black+Metal',
                '&style=Doo+Wop',
                '&style=Doom+Metal',
                '&style=Dream+Pop',
                '&style=Emo',
                '&style=Ethereal',
                '&style=Folk+Metal',
                '&style=Folk+Rock',
                '&style=Funeral+Doom+Metal',
                '&style=Funk+Metal',
                '&style=Garage+Rock',
                '&style=Glam',
                '&style=Goregrind',
                '&style=Goth+Rock',
                '&style=Gothic+Metal',
                '&style=Grindcore',
                '&style=Groove+Metal',
                '&style=Grunge',
                '&style=Hard+Rock',
                '&style=Heavy+Metal',
                '&style=Horror+Rock',
                '&style=Indie+Rock',
                '&style=Industrial+Metal',
                '&style=J-Rock',
                '&style=Jangle+Pop',
                '&style=K-Rock',
                '&style=Krautrock',
                '&style=Lo-Fi',
                '&style=Lounge',
                '&style=Math+Rock',
                '&style=Melodic+Death+Metal',
                '&style=Melodic+Hardcore',
                '&style=Metalcore',
                '&style=Mod',
                '&style=NDW',
                '&style=New+Wave',
                '&style=No+Wave',
                '&style=Noisecore',
                '&style=Nu+Metal',
                '&style=Oi',
                '&style=Parody',
                '&style=Pop+Punk',
                '&style=Pop+Rock',
                '&style=Pornogrind',
                '&style=Post+Rock',
                '&style=Post-Hardcore',
                '&style=Post-Metal',
                '&style=Post-Punk',
                '&style=Power+Metal',
                '&style=Power+Pop',
                '&style=Power+Violence',
                '&style=Prog+Rock',
                '&style=Progressive+Metal',
                '&style=Psychedelic+Rock',
                '&style=Psychobilly',
                '&style=Pub+Rock',
                '&style=Punk',
                '&style=Rock+&+Roll',
                '&style=Rock+Opera',
                '&style=Rockabilly',
                '&style=Shoegaze',
                '&style=Ska',
                '&style=Skiffle',
                '&style=Sludge+Metal',
                '&style=Soft+Rock',
                '&style=Southern+Rock',
                '&style=Space+Rock',
                '&style=Speed+Metal',
                '&style=Stoner+Rock',
                '&style=Surf',
                '&style=Swamp+Pop',
                '&style=Symphonic+Metal',
                '&style=Symphonic+Rock',
                '&style=Technical+Death+Metal',
                '&style=Thrash',
                '&style=Twist',
                '&style=Viking+Metal',
                '&style=Yé-Yé',
                '&style=Cabaret',
                '&style=Musical',
                '&style=Score',
                '&style=Soundtrack',
                '&style=Theme',
                '&style=Vaudeville',
                '&style=Video+Game+Music',
                '']

        sellers = ['Criminal-Rewind', 'ellaguru', 'Morpho_Chicago',
        'RoundTripRecords', 'ToneDeafRecords', 'Wild_Prairie', 
        'BucketOBlood', 'Meteor_Gem', 'lets_boogie_records', 'vvmo', 
        'Treasuregate', 'ShadyRest.Chicago', '606records', 'bluevillagevinyl', 
        'cheapkissrecords', 'TheConservatoryVinyl', 'thedenrecords', 'trustyspot', 
        'WeirdsvilleRecords', 'DetroitRecordClub', 'UHF-Records', 'streetcorner12', 
        'bradhales', 'dearbornm-farmington', 'RockCityMusicCo', 'Hoppingator', 
        'dearbornmusic', 'Slickdiscmusic', 'undergroundsoundsmi', 'TechniqueRecords', 
        'SweatRecords', 'Vinylasylum', 'Retrofit_Records', 'HearAgainRecords', 
        'groovyrecordsdeland', 'Ledzappa1956', 'secretsounds', 'Truetilldeathrecords', 
        'eraser.jax', 'tonevendor', 'deepthoughtsjp', 'GordonLaSalleVinyl', 
        'WantListRecords', 'planetrecords', 'armageddonshop', 'Villagevinylandhifi', 
        'WannaHearIt', 'lockedgroovellc', 'dj.mikie.love.s', 'normalsrecords', 
        'deepgroovesounds1', 'BabysOnFireBaltimore', 'JeffmanMusicEmporium', 
        'statestreetrecords', 'gethiprecordings', 'jerrysrecords', 'RevolverRecordsInc', 
        'blackdotsbuffalo', 'PrincetonRecordEx', 'recordrunnerusa', 'academyrecords', 
        'VinylFantasyBrooklyn', 'Factory-Record', 'humanheadnyc', 'JahAbrams', 
        'scottisrecordshop', 'recordgrouchbklyn', 'generationrecords', 
        'headsoundsrecords', 'facerecordsnyc', 'needleandgrooverec', 
        'RoughTradeNYC', 'MUSICONNECTION', 'longgoneday1', 'swoopy', 
        'Black_Gold_Brooklyn', 'Psychic_Brooklyn', 'almostready', 'ez2collect2', 
        'LooneyTunesCDs', 'justtracks', 'thevinylplant', 'DeepCutsRecordStore', 
        'hopfidelity', 'electric_avenue', 'ByrdlandRecords', 'Jointcustodydc', 
        'RecordExchangeofSS', 'Mobius_Records', 'donutshoppe', 'IRREst.2022',  
        'innergrooverecs', 'skyvalley420', 'timzatz', 'tunesonline', 'recordmuseum', 
        'phidelityrecords', 'Factory-Record', 'vinyl_dinosaur', 'clariziomusic', 
        'EastonExchange', 'doubledeckerrecords', 'RECREV', 'Young-Ones-Records', 
        'VertigoMusic449', 'WhitsEndTrading', 'impulsebuyrecords', 
        'Lititz_Music_Co.', 'MUSICALENERGIdotCOM', 'rebrecords-md', 
        'thevinylgarageus', 'admiralanalogs', 'FuzzyDogVintage',  'smashdc',
        'RecordExchangeofSS', 'YellowKShop', 'solarmountainrecords', 
        'recordsfromjupiter','rainbowrecordsde', 'extendedplay19971', 
        'philadelphiamusic', 'brewerytownbeats', 'creep-records', 
        'MilkcrateCafe', 'vinylaltar', 'commonbeatmusic', 'dreaminghuman', 
        'sitandspinrecords', 'Betternowrecords', 'impressionsphilly',
        'BullTrax', 'CTshop45s', 'bordentownrecords', 'pop.market', 
        'VinylShopUS', 'kennyosrecords', 'stevierayvinyl', 'mhamilamelton',
        'dorightman', 'recordsbymail', 'AlexanderCogs', 'Rose.Thyme', 
        'foreveryoungrecords', 'super.soul.records', 'thewaxhut',
        'lewisdene', 'Niksvinyl', 'ShinylVinyl', 'BrothersRecords',
        'CD_WAREHOUSE_817' , 'MRCLEANWAX', 'ryanrecords', 
        'Boom_Service' ,'Armo-15' ,'Honeysmush_Records', 'GROOVEENT',
        'cjohnson22463', 'letitberarities', 'Kozuch438', 
        'Redscroll', 'kent221', 'mstaurolite']

        for url in urls:
            for genre in genres:
                for seller in sellers:
                    for style in styles:
                        urlnew = url + seller + '/profile?format=Vinyl' + genre + style
                        yield scrapy.Request(url=urlnew, callback=self.parse)


    def parse(self, response):
  #      listings = []
        for listing in response.xpath('//tr[@class="shortcut_navigable "]'):
            yield{
                'title' : response.xpath('//a[@class="item_description_title"]/text()').get(),
                'label' : response.xpath('//p[@class="hide_mobile label_and_cat"]/a/text()').get(),
                'itemCatNo' : response.xpath('//p[@class="hide_mobile label_and_cat"]/span[@class="item_catno"]/text()').get(),
                'sleeveCondition' : response.xpath('//span[@class="item_sleeve_condition"]/text()').get(),
                'rUrl' : response.xpath('//a[@class="item_release_link hide_mobile"]').attrib['href'],
                'lUrl' : response.xpath('//a[@class="item_description_title"]').attrib['href'],
                'price' : response.xpath('//span[@class="price"]/text()').get()
            }

            # thisListing = Listing()
            # thisListing['title'] = title
            # thisListing['labelCat'] = labelCat
            # thisListing['itemCatNo'] = itemCatNo
            # thisListing['sleeveCondition'] = sleeveCondition
            # thisListing['rUrl'] = rUrl
            # thisListing['price'] = price
            # listings.append(thisListing)

        next_page = response.xpath('//a[@class="pagination_next"]').attrib['href']
        if next_page is not None:
            next_page = response.urljoin(next_page)
            yield scrapy.Request(next_page, callback=self.parse)

