import scrapy
from vinyl_crawler.items import Listing

class RecordlistingsPySpider(scrapy.Spider):
    name = 'discogsListings'
    allowed_domains = ['www.discogs.com']
    listings = []

    def start_requests(self):
        urls = ['https://www.discogs.com/seller/']
                
        genres = ['&genre=Electronic',
                  '&genre=Hip+Hop',
                  '&genre=Jazz',
                  '&genre=Folk%2C+World%2C+%26+Country',
                  '&genre=Classical',
                  '&genre=Stage+%26+Screen',
                  '&genre=Blues',
                  '&genre=Non-Music',
                  '&genre=Reggae',
                  '&genre=Children%27s',
                  '&genre=Brass+%26+Military'
                  '&genre=Funk+%2F+Soul',
                  '&genre=Pop',
                  '&genre=Rock',
                  ]

        styles = ['&style=Pop+Rock',
                  '&style=Soul',
                  '&style=Country',
                  '&style=Disco',
                  '&style=Vocal',
                  '&style=Funk',
                  '&style=',
                  '&style=House',
                  '&style=Rock+%26+Roll',
                  '&style=Synth-pop',
                  '&style=Rhythm+%26+Blues',
                  '&style=Punk',
                  '&style=Psychedelic+Rock',
                  '&style=Folk+Rock',
                  '&style=Easy+Listening',
                  '&style=Classic+Rock',
                  '&style=Ballad',
                  '&style=Blues+Rock',
                  '&style=Indie+Rock',
                  '&style=Folk',
                  '&style=Soft+Rock',
                  '&style=Hard+Rock',
                  '&style=Soundtrack',
                  '&style=Alternative+Rock',
                  '&style=Experimental',
                  '&style=Country+Rock',
                  '&style=Electro',
                  '&style=Hardcore',
                  '&style=New+Wave',
                  '&style=Garage+Rock',
                  '&style=Big+Band',
                  '&style=Prog+Rock',
                  '&style=Romantic',
                  '&style=Gospel',
                  '&style=Techno',
                  '&style=Jazz-Funk',
                  '&style=Swing',
                  '&style=Dancehall',
                  '&style=RnB/Swing',
                  '&style=Doo+Wop',
                  '&style=Deep+House',
                  '&style=Soul-Jazz',
                  '&style=Downtempo',
                  '&style=Fusion',
                  '&style=Classical',
                  '&style=Heavy+Metal',
                  '&style=Modern',
                  '&style=Ambient',
                  '&style=Comedy',
                  '&style=Rockabilly',
                  '&style=Garage+House',
                  '&style=Musical',
                  '&style=Jazz-Rock',
                  '&style=Art+Rock',
                  '&style=Baroque',
                  '&style=Theme',
                  '&style=Acoustic',
                  '&style=Contemporary+Jazz',
                  '&style=Bop',
                  '&style=Latin+Jazz',
                  '&style=Power+Pop',
                  '&style=Southern+Rock',
                  '&style=Bluegrass',
                  '&style=Reggae',
                  '&style=Score',
                  '&style=Dub',
                  '&style=Contemporary+R%26B',
                  '&style=Instrumental',
                  '&style=Cool+Jazz',
                  '&style=Novelty',
                  '&style=Tech+House',
                  '&style=Hard+Bop',
                  '&style=Noise',
                  '&style=Surf',
                  '&style=Opera',
                  '&style=Spoken+Word',
                  '&style=Gangsta',
                  '&style=Religious',
                  '&style=Trance',
                  '&style=Roots+Reggae',
                  '&style=Contemporary',
                  '&style=Avantgarde',
                  '&style=Post-Punk',
                  '&style=Breakbeat',
                  '&style=Progressive+House',
                  '&style=Beat',
                  '&style=Freestyle',
                  '&style=Abstract',
                  '&style=Smooth+Jazz',
                  '&style=Black+Metal',
                  '&style=Dixieland',
                  '&style=Post+Bop',
                  '&style=Boogie',
                  '&style=Glam',
                  '&style=Minimal',
                  '&style=Drum+n+Bass',
                  '&style=Pop+Rap',
                  '&style=Breaks',
                  '&style=Industrial',
                  '&style=Death+Metal',
                  '&style=Chanson',
                  '&style=Neo-Classical',
                  '&style=Choral',
                  '&style=Early',
                  '&style=Impressionist',
                  '&style=Medieval',
                  '&style=Modern',
                  '&style=Neo-Romantic',
                  '&style=Operetta',
                  '&style=Oratorio',
                  '&style=Post-Modern',
                  '&style=Renaissance',
                  '&style=Serial',
                  '&style=Twelve-tone',
                  '&style=Zarzuela',
                  '&style=Bleep',
                  '&style=Breakbeat',
                  '&style=Broken+Beat',
                  '&style=Chillwave',
                  '&style=Chiptune',
                  '&style=Dance-pop',
                  '&style=Dark+Ambient',
                  '&style=Darkwave',
                  '&style=Deep+Techno',
                  '&style=Disco+Polo',
                  '&style=Donk',
                  '&style=Doomcore',
                  '&style=Downtempo',
                  '&style=Drone',
                  '&style=Dub+Techno',
                  '&style=Dubstep',
                  '&style=Dungeon+Synth',
                  '&style=EBM',
                  '&style=Electro+House',
                  '&style=Electro+Swing',
                  '&style=Electroacoustic',
                  '&style=Euro+House',
                  '&style=Euro-Disco',
                  '&style=Eurobeat',
                  '&style=Eurodance',
                  '&style=Experimental',
                  '&style=Footwork',
                  '&style=Fonkot',
                  '&style=Future+Jazz',
                  '&style=Gabber',
                  '&style=Ghetto',
                  '&style=Ghetto+House',
                  '&style=Ghettotech',
                  '&style=Glitch',
                  '&style=Glitch+Hop',
                  '&style=Goa+Trance',
                  '&style=Grime',
                  '&style=Halftime',
                  '&style=Hands+Up',
                  '&style=Happy+Hardcore',
                  '&style=Hard+Beat',
                  '&style=Hard+House',
                  '&style=Hard+Techno',
                  '&style=Hard+Trance',
                  '&style=Hardcore',
                  '&style=Hardstyle',
                  '&style=Harsh+Noise+Wall',
                  '&style=hi+NRG',
                  '&style=Hip+Hop',
                  '&style=Hip-House',
                  '&style=IDM',
                  '&style=Illbient',
                  '&style=Italo+House',
                  '&style=Italodance',
                  '&style=J-Core',
                  '&style=Jazzdance',
                  '&style=Jersey+Club',
                  '&style=Juke',
                  '&style=Jumpstyle',
                  '&style=Jungle',
                  '&style=Latin',
                  '&style=Leftfield',
                  '&style=Lento+Violento',
                  '&style=Makina',
                  '&style=Minimal',
                  '&style=Minimal+Techno',
                  '&style=Modern+Classical',
                  '&style=Moombahton',
                  '&style=Neo+Trance',
                  '&style=musique+concr%C3%A8te',
                  '&style=Neofolk',
                  '&style=Nerdcore+Techno',
                  '&style=New+Age',
                  '&style=New+Beat',
                  '&style=Noise',
                  '&style=Nu-Disco',
                  '&style=Power+Electronics',
                  '&style=Progressive+Breaks',
                  '&style=Progressive+House',
                  '&style=Progressive+Trance',
                  '&style=Psy-Trance',
                  '&style=Rhythmic+Noise',
                  '&style=Schranz',
                  '&style=Skweee',
                  '&style=Sound+Collage',
                  '&style=Speedcore',
                  '&style=Speed+Garage',
                  '&style=Synthwave',
                  '&style=Synth-Pop',
                  '&style=Tech-House',
                  '&style=Tech-Trance',
                  '&style=Tribal',
                  '&style=Tribal+House',
                  '&style=Trip+Hop',
                  '&style=Tropical+House',
                  '&style=UK+Funky',
                  '&style=UK+Garage',
                  '&style=Vaporwave',
                  '&style=Witch+House',
                  ''
                  ]

        sellers = ['Criminal-Rewind', 'ellaguru', 'Morpho_Chicago',
        'RoundTripRecords', 'ToneDeafRecords', 'Wild_Prairie', 
        'BucketOBlood', 'Meteor_Gem', 'lets_boogie_records', 'vvmo', 
        'Treasuregate', 'ShadyRest.Chicago', '606records', 'bluevillagevinyl', 
        'cheapkissrecords', 'TheConservatoryVinyl', 'thedenrecords', 'trustyspot', 
        'WeirdsvilleRecords', 'DetroitRecordClub', 'UHF-Records', 'streetcorner12', 
        'bradhales', 'dearbornm-farmington', 'RockCityMusicCo', 'Hoppingator', 
        'dearbornmusic', 'Slickdiscmusic', 'undergroundsoundsmi', 'TechniqueRecords', 
        'SweatRecords', 'Vinylasylum', 'Retrofit_Records', 'HearAgainRecords', 
        'groovyrecordsdeland', 'Ledzappa1956', 'secretsounds', 'Truetilldeathrecords', 
        'eraser.jax', 'tonevendor', 'deepthoughtsjp', 'GordonLaSalleVinyl', 
        'WantListRecords', 'planetrecords', 'armageddonshop', 'Villagevinylandhifi', 
        'WannaHearIt', 'lockedgroovellc', 'dj.mikie.love.s', 'normalsrecords', 
        'deepgroovesounds1', 'BabysOnFireBaltimore', 'JeffmanMusicEmporium', 
        'statestreetrecords', 'gethiprecordings', 'jerrysrecords', 'RevolverRecordsInc', 
        'blackdotsbuffalo', 'PrincetonRecordEx', 'recordrunnerusa', 'academyrecords', 
        'VinylFantasyBrooklyn', 'Factory-Record', 'humanheadnyc', 'JahAbrams', 
        'scottisrecordshop', 'recordgrouchbklyn', 'generationrecords', 
        'headsoundsrecords', 'facerecordsnyc', 'needleandgrooverec', 
        'RoughTradeNYC', 'MUSICONNECTION', 'longgoneday1', 'swoopy', 
        'Black_Gold_Brooklyn', 'Psychic_Brooklyn', 'almostready', 'ez2collect2', 
        'LooneyTunesCDs', 'justtracks', 'thevinylplant', 'DeepCutsRecordStore', 
        'hopfidelity', 'electric_avenue', 'ByrdlandRecords', 'Jointcustodydc', 
        'RecordExchangeofSS', 'Mobius_Records', 'donutshoppe', 'IRREst.2022',  
        'innergrooverecs', 'skyvalley420', 'timzatz', 'tunesonline', 'recordmuseum', 
        'phidelityrecords', 'Factory-Record', 'vinyl_dinosaur', 'clariziomusic', 
        'EastonExchange', 'doubledeckerrecords', 'RECREV', 'Young-Ones-Records', 
        'VertigoMusic449', 'WhitsEndTrading', 'impulsebuyrecords', 
        'Lititz_Music_Co.', 'MUSICALENERGIdotCOM', 'rebrecords-md', 
        'thevinylgarageus', 'admiralanalogs', 'FuzzyDogVintage',  'smashdc',
        'RecordExchangeofSS', 'YellowKShop', 'solarmountainrecords', 
        'recordsfromjupiter','rainbowrecordsde', 'extendedplay19971', 
        'philadelphiamusic', 'brewerytownbeats', 'creep-records', 
        'MilkcrateCafe', 'vinylaltar', 'commonbeatmusic', 'dreaminghuman', 
        'sitandspinrecords', 'Betternowrecords', 'impressionsphilly',
        'BullTrax', 'CTshop45s', 'bordentownrecords', 'pop.market', 
        'VinylShopUS', 'kennyosrecords', 'stevierayvinyl', 'mhamilamelton',
        'dorightman', 'recordsbymail', 'AlexanderCogs', 'Rose.Thyme', 
        'foreveryoungrecords', 'super.soul.records', 'thewaxhut',
        'lewisdene', 'Niksvinyl', 'ShinylVinyl', 'BrothersRecords',
        'CD_WAREHOUSE_817' , 'MRCLEANWAX', 'ryanrecords', 
        'Boom_Service' ,'Armo-15' ,'Honeysmush_Records', 'GROOVEENT',
        'cjohnson22463', 'letitberarities', 'Kozuch438', 
        'Redscroll', 'kent221', 'mstaurolite']

        for url in urls:
            for genre in genres:
                for seller in sellers:
                    for style in styles:
                        urlnew = url + seller + '/profile?format=Vinyl' + genre + style
                        yield scrapy.Request(url=urlnew, callback=self.parse)


    def parse(self, response):
  #      listings = []
        for listing in response.xpath('//tr[@class="shortcut_navigable "]'):
            yield{
                'title' : response.xpath('//a[@class="item_description_title"]/text()').get(),
                'label' : response.xpath('//p[@class="hide_mobile label_and_cat"]/a/text()').get(),
                'itemCatNo' : response.xpath('//p[@class="hide_mobile label_and_cat"]/span[@class="item_catno"]/text()').get(),
                'sleeveCondition' : response.xpath('//span[@class="item_sleeve_condition"]/text()').get(),
                'rUrl' : response.xpath('//a[@class="item_release_link hide_mobile"]').attrib['href'],
                'lUrl' : response.xpath('//a[@class="item_description_title"]').attrib['href'],
                'price' : response.xpath('//span[@class="price"]/text()').get()
            }

            # thisListing = Listing()
            # thisListing['title'] = title
            # thisListing['labelCat'] = labelCat
            # thisListing['itemCatNo'] = itemCatNo
            # thisListing['sleeveCondition'] = sleeveCondition
            # thisListing['rUrl'] = rUrl
            # thisListing['price'] = price
            # listings.append(thisListing)

        next_page = response.xpath('//a[@class="pagination_next"]').attrib['href']
        if next_page is not None:
            next_page = response.urljoin(next_page)
            yield scrapy.Request(next_page, callback=self.parse)

